// Seed data for the 12 core SpiritualCharacter nodes.
// Written once to Firestore via the "Seed Characters" button in CharacterIntelligencePanel.
// All content is based on canonical Hindu/Buddhist tradition.
// AI contributions are marked ai_draft — founder verification required before isPublic.

import type {
  SpiritualCharacter,
  SpiritualRelationship,
} from "../types/temple-vault";

// Convenience: build a MultilingualText
function ml(
  sanskrit: string,
  nepali: string,
  english: string,
  hindi?: string,
): { sanskrit: string; nepali: string; english: string; hindi?: string } {
  return { sanskrit, nepali, english, ...(hindi ? { hindi } : {}) };
}

// IDs are fixed so relationships can reference them reliably
export const SEED_IDS = {
  shiva:          "seed_shiva",
  parvati:        "seed_parvati",
  ganesha:        "seed_ganesha",
  krishna:        "seed_krishna",
  radha:          "seed_radha",
  hanuman:        "seed_hanuman",
  rama:           "seed_rama",
  saraswati:      "seed_saraswati",
  lakshmi:        "seed_lakshmi",
  vishnu:         "seed_vishnu",
  shankaracharya: "seed_shankaracharya",
  buddha:         "seed_buddha",
} as const;

export const SPIRITUAL_CHARACTER_SEEDS: Array<Omit<SpiritualCharacter, "ownerId" | "createdAt" | "updatedAt"> & { id: string }> = [

  // ── Shiva ─────────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.shiva,
    characterType:  "deity",
    icon:           "🕉",
    chamberTheme:   "shiva",
    primaryName:    ml("शिव", "शिव", "Shiva", "शिव"),
    alternateNames: [
      ml("महादेव", "महादेव", "Mahadeva — The Great God"),
      ml("नटराज", "नटराज", "Nataraja — Lord of the Cosmic Dance"),
      ml("पशुपति", "पशुपति", "Pashupati — Lord of all Beings"),
      ml("महाकाल", "महाकाल", "Mahakala — Lord of Time"),
      ml("भोलेनाथ", "भोलेनाथ", "Bholenath — The Simple, Innocent Lord"),
      ml("त्र्यम्बक", "त्र्यम्बक", "Tryambaka — The Three-Eyed One"),
    ],
    epithets:       ["Destroyer", "Transformer", "The Auspicious", "Consciousness Itself"],
    traditions:     ["shaiva"],
    primaryTradition: "shaiva",
    essence:        ml(
      "शुद्धचैतन्यम्, महेश्वरः",
      "शुद्ध चेतना, माया को नाशक, परम् शिव",
      "Pure Consciousness — destroyer of illusion, source of all transformation",
      "शुद्ध चेतना, ब्रह्मांड के संहारक",
    ),
    philosophicalNote: "In Shaiva philosophy, Shiva is Paramashiva — the absolute, unchanging ground of all existence. He is not merely the destroyer; he destroys what is unreal so that what is real may remain. Consciousness itself is Shiva. Everything arises within Shiva's awareness.",
    devotionalNote: "Devotees experience Shiva as the supremely approachable god — one who drinks poison to protect the world, who lives as a renunciant in the cremation ground, who is equally the terrifying Bhairava and the gentle Shankara. He grants boons easily — Bholenath, the innocent one.",
    symbols:        ["त्रिशूल (trident)", "डमरु (damaru)", "तृतीय नेत्र (third eye)", "चन्द्रकला (crescent moon)", "गङ्गा (Ganga in hair)", "नीलकण्ठ (blue throat)", "भस्म (ash)", "नन्दी (Nandi the bull)"],
    colors:         ["ash-white", "deep-blue", "silver"],
    iconographicDesc: "Shiva in meditation posture (padmasana), ash-smeared body, matted hair (jata) bearing the crescent moon and Ganga. Third eye on forehead. Trident in right hand, damaru drum. Nandi seated before him. Rudraksha mala. Set in Mount Kailash or cremation ground (shmashana).",
    vehicleMount:   "नन्दी (Nandi — sacred white bull)",
    primaryRasa:    "rudra",
    moods:          ["शान्त — Shiva in deep samadhi", "रुद्र — Shiva as Bhairava, destroyer of fear", "नटराज — Shiva as the cosmic dancer dissolving and recreating"],
    coreTeachings:  [
      ml("ॐ नमः शिवाय", "ॐ नमः शिवाय", "Salutation to the auspicious Shiva — the five syllables correspond to the five elements"),
      ml("शिवोऽहम्", "म नै शिव हुँ", "I am Shiva — the realization of one's own nature as pure consciousness"),
      ml("सत्यं ज्ञानमनन्तं ब्रह्म", "सत्य, ज्ञान, अनन्त — यी ब्रह्म हुन्", "Truth, Knowledge, Infinity — this is Brahman"),
    ],
    keyShlokas:     [
      "ॐ नमः शिवाय — the Panchakshara Mantra",
      "महामृत्युञ्जय मन्त्र: ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्...",
    ],
    leelaHighlights: [
      ml("नीलकण्ठ", "समुद्र मन्थनमा विष पिउनु", "Drinking the halahala poison during Samudra Manthan to save the cosmos — becoming Neelakantha, the blue-throated one"),
      ml("तांडव", "ब्रह्माण्डको विसर्जन नृत्य", "The Tandava — Shiva's cosmic dance of creation and dissolution at Chidambaram"),
      ml("दक्ष यज्ञ", "सतीको बलिदान र शोक", "Sati's self-immolation at Daksha's yajna — Shiva's grief and the dissolution of the world"),
    ],
    spouseIds:      [SEED_IDS.parvati],
    childIds:       [SEED_IDS.ganesha],
    semanticAtomIds: ["dharma", "moksha", "maya", "shakti", "tapas", "om"],
    scriptureRefs:  ["Shiva Purana", "Shaiva Agamas", "Rigveda — Rudra Hymns (RV 2.33)", "Linga Purana", "Skanda Purana"],
    bhajanRefs:     ["ॐ नमः शिवाय भजन", "महामृत्युञ्जय जाप", "भज गोविन्दम् (Shankaracharya)"],
    festivals:      ["महाशिवरात्रि (Mahashivaratri)", "श्रावण सोमवार", "प्रदोष व्रत"],
    mantras:        ["ॐ नमः शिवाय", "ॐ त्र्यम्बकं यजामहे...", "शिव शिव शिव शम्भो"],
    canonicalMediaContext: "",
    primarySources: ["Shiva Purana", "Shaiva Agamas", "Linga Purana"],
    verified:       false,
    visibility:     "private",
  },

  // ── Parvati / Devi ────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.parvati,
    characterType:  "deity",
    icon:           "🌸",
    chamberTheme:   "devi",
    primaryName:    ml("पार्वती", "पार्वती", "Parvati — Daughter of the Mountain"),
    alternateNames: [
      ml("देवी", "देवी", "Devi — The Goddess"),
      ml("उमा", "उमा", "Uma — Light / The Gracious"),
      ml("गौरी", "गौरी", "Gauri — The Golden / Fair One"),
      ml("दुर्गा", "दुर्गा", "Durga — The Invincible"),
      ml("काली", "काली", "Kali — The Dark One, Destroyer of Time"),
      ml("जगदम्बा", "जगदम्बा", "Jagadamba — Mother of the Universe"),
    ],
    epithets:       ["Divine Feminine", "Shakti — the Universal Energy", "Mahashakti"],
    traditions:     ["shakta", "shaiva"],
    primaryTradition: "shakta",
    essence:        ml(
      "परमा शक्तिः, जगन्माता",
      "परम शक्ति, सृष्टि-पालन-विनाशकर्त्री, ब्रह्माण्डकी माता",
      "Supreme Energy — the active power behind all creation, preservation, and dissolution",
    ),
    philosophicalNote: "In Shakta philosophy, Devi is not a goddess among gods — she is the ultimate reality itself. Brahman with shakti (power) is Shiva; Brahman as shakti is Devi. The Devi Mahatmya states: she is consciousness, she is the universe, she is time, she is all.",
    devotionalNote: "As Parvati, she is the ideal companion, meditator, and mother. As Durga she rides a lion and defeats the Buffalo Demon (Mahishasura) — dharma over adharma. As Kali she is fierce grace that destroys the ego's deepest roots. All forms are one mother.",
    symbols:        ["कमल (lotus)", "त्रिशूल (trident as Durga)", "सिंह (lion as Durga)", "कपाल (skull bowl as Kali)", "श्वेत वस्त्र (white garments)", "माँ का आँचल (motherly embrace)"],
    colors:         ["gold", "deep-crimson", "white", "dark-indigo"],
    iconographicDesc: "As Parvati: golden-complexioned, seated beside Shiva on Kailash or in her own grace. As Durga: eighteen-armed, riding a lion, defeating Mahishasura. As Kali: dark-complexioned, standing on Shiva, garlanded with skulls, sword in hand, fierce yet protective.",
    primaryRasa:    "vira",
    moods:          ["वात्सल्य — as the devoted mother holding Ganesha", "रुद्र — as Kali/Durga destroying evil", "शान्त — as Uma in meditative union with Shiva"],
    coreTeachings:  [
      ml("जगत् सत्यम्", "संसार सत्य हो — देवीको शक्तिले", "The world is real — for Devi is its substance, not illusion but pure energy"),
      ml("स्त्री-शक्तिः परमा", "स्त्री शक्ति परम हो", "The power of the feminine is the supreme force — not subordinate but the ground of being"),
    ],
    keyShlokas:     [
      "या देवी सर्वभूतेषु शक्तिरूपेण संस्थिता — Devi Mahatmya",
      "नमस्तस्यै नमस्तस्यै नमस्तस्यै नमो नमः",
    ],
    leelaHighlights: [
      ml("महिषासुरमर्दिनी", "महिषासुर बध", "Slaying of Mahishasura — Durga's battle to restore cosmic order"),
      ml("शक्ति परीक्षा", "शिवलाई जगाउन तपस्या", "Parvati's thousand-year tapas to win Shiva — the power of devotion"),
    ],
    spouseIds:      [SEED_IDS.shiva],
    childIds:       [SEED_IDS.ganesha],
    semanticAtomIds: ["shakti", "maya", "dharma", "bhakti", "tapas"],
    scriptureRefs:  ["Devi Mahatmya (Markandeya Purana 81–93)", "Devi Bhagavatam", "Shiva Purana", "Lalita Sahasranama"],
    festivals:      ["नवरात्रि (Navaratri)", "दुर्गा पूजा", "तीज", "काली पूजा"],
    mantras:        ["ॐ दुं दुर्गायै नमः", "ॐ क्रीं कालिकायै नमः", "या देवी सर्वभूतेषु..."],
    canonicalMediaContext: "",
    primarySources: ["Devi Mahatmya", "Devi Bhagavatam", "Shakta Agamas"],
    verified:       false,
    visibility:     "private",
  },

  // ── Ganesha ───────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.ganesha,
    characterType:  "deity",
    icon:           "🐘",
    chamberTheme:   "default",
    primaryName:    ml("गणेश", "गणेश", "Ganesha — Lord of Hosts"),
    alternateNames: [
      ml("विनायक", "विनायक", "Vinayaka — The Remover"),
      ml("गणपति", "गणपति", "Ganapati — Leader of Ganas"),
      ml("विघ्नहर", "विघ्नहर", "Vighnahara — Remover of Obstacles"),
      ml("प्रथमपूज्य", "प्रथमपूज्य", "Prathamapujya — First to be Worshipped"),
      ml("लम्बोदर", "लम्बोदर", "Lambodara — The Pot-bellied One"),
      ml("एकदन्त", "एकदन्त", "Ekadanta — Single Tusked"),
    ],
    epithets:       ["Lord of New Beginnings", "Patron of Arts and Sciences", "God of Wisdom"],
    traditions:     ["shaiva", "ganapatya"],
    primaryTradition: "shaiva",
    essence:        ml(
      "विघ्नहर्ता, बुद्धिदाता",
      "बाधा हटाउने, बुद्धि दिने देवता — हरेक शुभ कार्यको आरम्भमा पूजनीय",
      "Remover of obstacles, bestower of wisdom — invoked at the beginning of every auspicious endeavour",
    ),
    philosophicalNote: "Ganesha's elephant head represents the jiva (individual soul) and his human body represents the universe. The broken tusk used to write the Mahabharata shows sacrifice of ego for cosmic purpose. His mouse vahana (ego riding under the elephant's wisdom) represents control over the small self.",
    devotionalNote: "Worshipped first — before any deity, before any undertaking. His large ears indicate he hears all prayers. His large belly contains the entire universe with equanimity. His gentle eyes observe without judgment.",
    symbols:        ["एकदन्त (single tusk)", "मोदक (sweet — wisdom)", "अङ्कुश (ankusha — goad)", "पाश (pasha — noose)", "मूषक (mouse vahana)", "हाथी का सिर (elephant head)"],
    colors:         ["vermilion", "gold", "red"],
    iconographicDesc: "Elephant-headed, pot-bellied, seated on a lotus or throne. Four arms: holds modak sweet, broken tusk, ankusha (goad), and pasha (noose). Mouse (Mushika) sits at his feet. Often red-orange complexion, adorned with flowers and marigold garlands.",
    vehicleMount:   "मूषक / Mushika (mouse)",
    primaryRasa:    "vatsalya",
    moods:          ["शान्त — as Vinayaka bestowing blessings", "आनन्द — playful, childlike divine"],
    coreTeachings:  [
      ml("विघ्नों का नाश", "बाधाहरू हट्छन्", "All obstacles dissolve — outer and inner — through Ganesha's grace"),
      ml("बुद्धि प्रमुखा", "बुद्धि नै प्रमुख शक्ति हो", "Intelligence is the primary power — Ganesha blesses right thinking"),
    ],
    keyShlokas:     [
      "ॐ गं गणपतये नमः",
      "वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ — Ganesha Shloka",
    ],
    leelaHighlights: [
      ml("दन्त-भंग", "एकदन्त भएको कथा", "Breaking his own tusk to write the Mahabharata as Vyasa dictated — sacrifice for cosmic purpose"),
    ],
    spouseIds:      [],
    childIds:       [],
    manifestationOfId: SEED_IDS.parvati,
    semanticAtomIds: ["dharma", "buddhi", "om"],
    scriptureRefs:  ["Ganapati Atharvashirsha", "Mudgala Purana", "Shiva Purana", "Mahabharata (scribe)"],
    festivals:      ["गणेश चतुर्थी", "विनायक चतुर्थी (monthly)"],
    mantras:        ["ॐ गं गणपतये नमः", "ॐ गणेशाय नमः", "वक्रतुण्ड महाकाय..."],
    canonicalMediaContext: "",
    primarySources: ["Ganapati Atharvashirsha", "Mudgala Purana"],
    verified:       false,
    visibility:     "private",
  },

  // ── Krishna ───────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.krishna,
    characterType:  "avatar",
    icon:           "🪷",
    chamberTheme:   "krishna",
    primaryName:    ml("कृष्ण", "कृष्ण", "Krishna — The Dark One / The All-Attractive"),
    alternateNames: [
      ml("गोविन्द", "गोविन्द", "Govinda — Lord of the Senses, Protector of Cows"),
      ml("माधव", "माधव", "Madhava — Lord of Lakshmi / Born of Spring"),
      ml("मुरलीधर", "मुरलीधर", "Muralidhara — Bearer of the Flute"),
      ml("गोपाल", "गोपाल", "Gopala — Cowherd, Protector"),
      ml("वासुदेव", "वासुदेव", "Vasudeva — Son of Vasudeva"),
      ml("श्यामसुन्दर", "श्यामसुन्दर", "Shyamasundara — The Beautiful Dark One"),
      ml("हरि", "हरि", "Hari — He who removes all sins"),
    ],
    epithets:       ["The Supreme Personality of Godhead", "Jagadguru — World Teacher", "Yogiraj"],
    traditions:     ["vaishnava"],
    primaryTradition: "vaishnava",
    essence:        ml(
      "परमात्मा, नित्यानन्दस्वरूपः",
      "दिव्य प्रेम, धर्म, र लीला — परमात्माको पूर्ण प्रकटन",
      "Divine love, eternal dharma, cosmic play — the complete manifestation of the Supreme",
    ),
    philosophicalNote: "In the Bhagavad Gita, Krishna reveals himself as the eternal, birthless, deathless atman underlying all beings. He teaches four paths to moksha: jnana (knowledge), bhakti (devotion), karma (action), raja (meditation). The entire Gita unfolds on one battlefield in one morning.",
    devotionalNote: "As a child in Vrindavan, Krishna embodies pure divine play (leela) — stealing butter, charming cowherdesses, playing his flute. As Arjuna's charioteer, he becomes the universal teacher. The combination of cosmic majesty and accessible love makes him uniquely beloved.",
    symbols:        ["मुरली (flute)", "मयूर पंख (peacock feather)", "पीत वस्त्र (yellow garment)", "कदम्ब वृक्ष (kadamba tree)", "सुदर्शन चक्र (Sudarshana Chakra)", "शंख पाञ्चजन्य", "वृन्दावन (Vrindavan)"],
    colors:         ["midnight-blue", "gold", "yellow"],
    iconographicDesc: "Krishna in tribhanga (triple-bend posture), playing the flute. Dark blue complexion, peacock feather crown, yellow garment, flower garland (vaijayanti). Sometimes shown with Radha beside him under a kadamba tree in Vrindavan. In Gita context: as charioteer holding reins, Arjuna behind him.",
    vehicleMount:   "गरुड (Garuda) as Vishnu; on foot / as charioteer in Gita",
    primaryRasa:    "madhurya",
    moods:          ["माधुर्य — flute-playing Krishna of Vrindavan with Radha", "सख्य — Krishna as Arjuna's charioteer-friend", "ऐश्वर्य — Vishwarupa, the cosmic form"],
    coreTeachings:  [
      ml("कर्मण्येवाधिकारस्ते", "कर्म गर्नु तिम्रो अधिकार हो, फल माग्न होइन", "You have a right to perform your duty but no right to the fruits — nishkama karma yoga"),
      ml("सर्वधर्मान् परित्यज्य मामेकं शरणं व्रज", "सबै धर्म छोडेर मलाई मात्र शरण आउ", "Abandon all dharmas and surrender to Me alone — the path of total surrender"),
      ml("योगस्थः कुरु कर्माणि", "योगमा स्थित भई कर्म गर", "Established in yoga, perform action — act without attachment"),
    ],
    keyShlokas:     [
      "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन — Bhagavad Gita 2.47",
      "सर्वधर्मान् परित्यज्य मामेकं शरणं व्रज — Bhagavad Gita 18.66",
      "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत — Bhagavad Gita 4.7",
    ],
    leelaHighlights: [
      ml("भगवद्गीता", "कुरुक्षेत्रमा अर्जुनलाई उपदेश", "The Bhagavad Gita — Krishna's discourse to Arjuna on the battlefield of Kurukshetra"),
      ml("विश्वरूप दर्शन", "विश्वरूप देखाउनु", "Vishwaroopa Darshana — revealing the universal cosmic form to Arjuna"),
      ml("रास लीला", "वृन्दावनमा रासलीला", "Rasa Leela — the divine dance with the gopis in Vrindavan, symbol of the soul's union with the divine"),
      ml("गोवर्धन धारण", "इन्द्र को क्रोध बाट गाउँलेलाई बचाउनु", "Lifting Govardhana Hill to protect the village from Indra's wrath"),
    ],
    spouseIds:      [SEED_IDS.radha],
    manifestationOfId: SEED_IDS.vishnu,
    semanticAtomIds: ["dharma", "karma", "bhakti", "yoga", "moksha", "leela"],
    scriptureRefs:  ["भगवद्गीता (Bhagavad Gita)", "श्रीमद्भागवत (Srimad Bhagavatam)", "Vishnu Purana", "Harivamsa"],
    bhajanRefs:     ["हरे कृष्ण महामन्त्र", "कृष्णं वन्दे जगद्गुरुम्", "मीराबाईका कृष्ण भजन"],
    festivals:      ["जन्माष्टमी (Janmashtami)", "होली (Holi)", "राधाष्टमी"],
    mantras:        ["ॐ नमो भगवते वासुदेवाय", "हरे कृष्ण हरे कृष्ण, कृष्ण कृष्ण हरे हरे"],
    canonicalMediaContext: "",
    primarySources: ["Bhagavad Gita", "Srimad Bhagavatam", "Vishnu Purana"],
    verified:       false,
    visibility:     "private",
  },

  // ── Radha ─────────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.radha,
    characterType:  "devotee_saint",
    icon:           "🌺",
    chamberTheme:   "bhakti",
    primaryName:    ml("राधा", "राधा", "Radha — The Supreme Devotee"),
    alternateNames: [
      ml("राधिका", "राधिका", "Radhika"),
      ml("वृषभानुजा", "वृषभानुजा", "Vrashabhanuaja — Daughter of Vrishabhanu"),
      ml("श्रीराधे", "श्रीराधे", "Sri Radhe — the Auspicious One"),
    ],
    epithets:       ["The Embodiment of Bhakti", "Hladini Shakti — Krishna's own bliss-potency"],
    traditions:     ["vaishnava"],
    primaryTradition: "vaishnava",
    essence:        ml(
      "परमभक्तिः, कृष्णह्लादिनीशक्तिः",
      "परम भक्तिको स्वरूप — कृष्णप्रेमको उच्चतम प्रकटन",
      "The embodiment of supreme devotion — the highest expression of love for Krishna",
    ),
    philosophicalNote: "In the Gaudiya Vaishnava tradition (Chaitanya Mahaprabhu), Radha is the hladini-shakti — Krishna's own bliss energy. She is not separate from Krishna; she is how Krishna experiences his own bliss. The Radha-Krishna relationship is the model of the soul's relationship to the Divine.",
    devotionalNote: "Radha does not merely love Krishna — she IS love. Her separation (viraha) from Krishna is seen in Bhakti tradition as the highest devotional state, where longing itself becomes the highest spiritual experience. Mirabai's bhajans channel this same madhurya bhakti.",
    symbols:        ["वृन्दावन (Vrindavan)", "कदम्ब वृक्ष", "युगल (Radha-Krishna together)", "निलुफर (blue lotus)"],
    colors:         ["golden", "rose", "blue"],
    iconographicDesc: "Radha stands beside Krishna under the kadamba tree in Vrindavan. Golden complexion, adorned with jewels and flowers. Often shown in a state of loving absorption, sometimes in the viraha pose (separation-longing). Always paired with Krishna in the classical image.",
    primaryRasa:    "madhurya",
    moods:          ["माधुर्य — in union with Krishna (samyoga)", "विरह — separation from Krishna (viraha) — the highest devotional pain"],
    coreTeachings:  [
      ml("प्रेम परमो धर्मः", "प्रेम नै परम धर्म हो", "Love is the supreme dharma — not rules, not ritual, but the pure love of the heart"),
    ],
    keyShlokas:     ["राधे राधे", "जय राधे जय राधे राधे"],
    leelaHighlights: [
      ml("रास लीला", "कृष्णसँग दिव्य रास", "The Rasa Leela — the sacred dance of Radha and Krishna, symbol of soul's union with God"),
    ],
    spouseIds:      [SEED_IDS.krishna],
    semanticAtomIds: ["bhakti", "leela", "madhurya"],
    scriptureRefs:  ["Srimad Bhagavatam (10th Skandha)", "Gita Govinda (Jayadeva)", "Brahma Vaivarta Purana"],
    bhajanRefs:     ["राधे राधे", "मीराबाईका भजन", "जय राधे जय कृष्णे"],
    festivals:      ["राधाष्टमी", "होली (Holi)"],
    mantras:        ["राधे राधे", "ॐ राधाकृष्णाभ्यां नमः"],
    canonicalMediaContext: "",
    primarySources: ["Gita Govinda (Jayadeva)", "Brahma Vaivarta Purana"],
    verified:       false,
    visibility:     "private",
  },

  // ── Hanuman ───────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.hanuman,
    characterType:  "deity",
    icon:           "🌟",
    chamberTheme:   "hanuman",
    primaryName:    ml("हनुमान्", "हनुमान", "Hanuman — The Devoted Servant"),
    alternateNames: [
      ml("पवनपुत्र", "पवनपुत्र", "Pavanputra — Son of Wind"),
      ml("मारुति", "मारुति", "Maruti — Son of Maruta (Wind)"),
      ml("बजरंगबली", "बजरंगबली", "Bajrangabali — The Strong as Diamond"),
      ml("महावीर", "महावीर", "Mahavira — The Great Hero"),
      ml("संकटमोचन", "संकटमोचन", "Sankatamochana — Remover of Calamities"),
      ml("केसरीनन्दन", "केसरीनन्दन", "Kesarinandana — Son of Kesari"),
    ],
    epithets:       ["Supreme Devotee", "Master of Grammar and Wisdom", "Chiranjeevi — Immortal"],
    traditions:     ["vaishnava", "shaiva"],
    primaryTradition: "vaishnava",
    essence:        ml(
      "परमभक्तः, शक्तिमान्",
      "राम-भक्तिको प्रतीक — शक्ति, बुद्धि र भक्तिको एकीकृत स्वरूप",
      "The embodiment of devotion combined with strength — power in service of the Divine",
    ),
    philosophicalNote: "Hanuman is the perfect example of how complete self-surrender (prapatti) to the Divine is not weakness but the source of boundless strength. He knows the Vedas, grammar (Ashtadhyayi), music, and all shastras — but uses all knowledge only in service.",
    devotionalNote: "When asked who he is, Hanuman said: 'In body I am the servant of Rama; in soul I am part of Rama; in truth I am Rama.' This three-level answer describes the progressive states of devotion. He is the doorway to Rama's grace.",
    symbols:        ["गदा (mace)", "राम-नाम हृदयमा (Rama's name on heart)", "पर्वत उठाउनु (lifting mountains)", "लङ्का दहन (burning Lanka)"],
    colors:         ["saffron", "orange", "vermilion"],
    iconographicDesc: "Hanuman in anjali posture (hands folded) before Rama and Sita, or in vira-asana (hero posture) with mace. Monkey form, saffron color, sacred thread (yajnopavita), Rama's name written on heart. Sometimes shown flying carrying Sanjeevani mountain.",
    primaryRasa:    "dasya",
    moods:          ["दास्य — humble servant at Rama's feet", "वीर — mighty warrior destroying asuras"],
    coreTeachings:  [
      ml("भक्तिः सेवा च शक्तिः", "भक्ति र सेवा नै शक्ति हो", "Devotion and service are the greatest strength — Hanuman combines all three"),
      ml("जय श्रीराम", "जय श्रीराम", "Jai Shri Ram — the name of Rama is the supreme mantra"),
    ],
    keyShlokas:     [
      "हनुमान चालीसा — तुलसीदास रचित",
      "मनोजवं मारुततुल्यवेगं...",
    ],
    leelaHighlights: [
      ml("सुन्दर काण्ड", "लङ्कामा सीताको खोजी", "Sundara Kanda — the search for Sita in Lanka, burning Lanka with his tail"),
      ml("सञ्जीवनी", "लक्ष्मणलाई बचाउन पर्वत उठाउनु", "Carrying the Sanjeevani mountain to save Lakshmana"),
    ],
    spouseIds:      [],
    childIds:       [],
    semanticAtomIds: ["bhakti", "dharma", "seva", "shakti"],
    scriptureRefs:  ["Valmiki Ramayana (Sundara Kanda)", "Ramacharitamanas (Tulsidas)", "Hanuman Chalisa"],
    festivals:      ["हनुमान जयन्ती", "राम नवमी"],
    mantras:        ["ॐ हनुमते नमः", "जय हनुमान ज्ञान गुण सागर", "हनुमान चालीसा"],
    canonicalMediaContext: "",
    primarySources: ["Valmiki Ramayana", "Ramacharitamanas"],
    verified:       false,
    visibility:     "private",
  },

  // ── Rama ──────────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.rama,
    characterType:  "avatar",
    icon:           "🏹",
    chamberTheme:   "default",
    primaryName:    ml("राम", "राम", "Rama — The Ideal One"),
    alternateNames: [
      ml("रघुनाथ", "रघुनाथ", "Raghunatha — Lord of the Raghu dynasty"),
      ml("मर्यादापुरुषोत्तम", "मर्यादापुरुषोत्तम", "Maryada Purushottama — The Perfect Man of Righteousness"),
      ml("राघव", "राघव", "Raghava — Descendant of Raghu"),
      ml("सीताराम", "सीताराम", "Sitaram — Rama of Sita"),
    ],
    epithets:       ["Embodiment of Dharma", "Ideal Son, Husband, King"],
    traditions:     ["vaishnava"],
    primaryTradition: "vaishnava",
    essence:        ml(
      "धर्मस्वरूपः, मर्यादापुरुषोत्तमः",
      "धर्मको मूर्त प्रतीक — हर परिस्थितिमा सही कार्य गर्ने आदर्श",
      "The living embodiment of dharma — ideal conduct in every role and situation",
    ),
    philosophicalNote: "Rama demonstrates dharma not as abstract law but as living conduct. As son, husband, brother, king — he shows the ideal. In Advaita, Ramachandra is Brahman itself appearing in human form to uphold dharma in every role.",
    devotionalNote: "Rama's name (Ram-Nam) is said to be the greatest mantra — 'Ram' contains the seed syllables of two supreme names (Ra from Narayana, Ma from Shiva). Gandhi's last words were 'He Ram.' The Ramayana is the story of every soul's journey to self-realization.",
    symbols:        ["धनुष (Kodanda bow)", "बाण (arrow)", "वनवास (forest exile — renunciation)"],
    colors:         ["blue", "green", "golden"],
    iconographicDesc: "Rama with bow and quiver of arrows, blue-complexioned or dark-hued, noble bearing, prince's crown. Often shown with Sita on his right, Lakshmana to his left, Hanuman at his feet in devotion. In Ramacharitamanas imagery: gentle, luminous, the ideal king.",
    vehicleMount:   "None (walks with Hanuman as companion)",
    primaryRasa:    "vira",
    moods:          ["वीर — warrior Rama defeating Ravana", "शान्त — meditating Rama in the forest", "करुण — Rama's grief at Sita's separation"],
    coreTeachings:  [
      ml("धर्मो रक्षति रक्षितः", "धर्मले रक्षा गर्छ र धर्मले रक्षित हुन्छ", "Dharma protects those who protect dharma"),
      ml("वचनं मे न मिथ्या स्यात्", "मेरो वचन कहिल्यै मिथ्या हुँदैन", "My word shall never be false — integrity above all"),
    ],
    keyShlokas:     ["श्री राम जय राम जय जय राम", "रामाय रामभद्राय रामचन्द्राय वेधसे..."],
    leelaHighlights: [
      ml("रावण वध", "रावणको वध", "Slaying of Ravana — the victory of dharma over adharma"),
      ml("वनवास", "१४ वर्ष वनवास", "14-year forest exile — accepting hardship in service of dharma"),
    ],
    spouseIds:      [],
    childIds:       [],
    manifestationOfId: SEED_IDS.vishnu,
    semanticAtomIds: ["dharma", "karma", "satya"],
    scriptureRefs:  ["Valmiki Ramayana", "Ramacharitamanas (Tulsidas)", "Adhyatma Ramayana"],
    festivals:      ["राम नवमी", "दीपावली (return to Ayodhya)"],
    mantras:        ["श्री राम जय राम जय जय राम", "ॐ श्री रामाय नमः"],
    canonicalMediaContext: "",
    primarySources: ["Valmiki Ramayana", "Ramacharitamanas"],
    verified:       false,
    visibility:     "private",
  },

  // ── Saraswati ─────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.saraswati,
    characterType:  "deity",
    icon:           "🎵",
    chamberTheme:   "default",
    primaryName:    ml("सरस्वती", "सरस्वती", "Saraswati — Goddess of Knowledge"),
    alternateNames: [
      ml("वाग्देवी", "वाग्देवी", "Vagdevi — Goddess of Speech"),
      ml("शारदा", "शारदा", "Sharada — The Autumnal Goddess"),
      ml("वीणापाणि", "वीणापाणि", "Veenapani — Holder of the Vina"),
      ml("हंसवाहिनी", "हंसवाहिनी", "Hamsavahini — Riding the Swan"),
    ],
    epithets:       ["Mother of the Vedas", "Bestower of Wisdom and Arts"],
    traditions:     ["shakta", "vedic"],
    primaryTradition: "shakta",
    essence:        ml(
      "ज्ञानदात्री, वाग्देवी",
      "ज्ञान, कला, र विद्याको देवी — शुद्ध बुद्धिको प्रतीक",
      "Goddess of knowledge, arts, wisdom — the pure intellect and creative power of the universe",
    ),
    philosophicalNote: "Saraswati represents vak — speech, the primordial power of language and meaning. The Vedas themselves are her body. Knowledge is not mere information but insight — she grants viveka (discrimination) between the real and unreal.",
    devotionalNote: "Students, poets, musicians, writers — all invoke Saraswati. Her white color represents purity of knowledge untainted by ego. Her swan distinguishes the real from the unreal (milk from water). She sits on a lotus — rooted in truth, unstained by the world.",
    symbols:        ["वीणा (vina — knowledge as music)", "पुस्तक (book — scriptures)", "हंस (swan — discrimination)", "श्वेत कमल (white lotus)", "माला (japa mala)", "श्वेत वस्त्र (white garment)"],
    colors:         ["white", "ivory", "gold"],
    iconographicDesc: "Saraswati in white garments, seated on a white lotus or swan. Four arms: holding vina (lute), book (Vedas), lotus, and japa mala. Sometimes two-armed in simpler form. Serene, pure expression, surrounded by the swan and peacock.",
    vehicleMount:   "हंस (Swan) — symbol of discrimination",
    primaryRasa:    "shanta",
    moods:          ["शान्त — the pure stillness of deep knowledge", "आनन्द — the joy of creative expression"],
    coreTeachings:  [
      ml("सा विद्या या विमुक्तये", "जे विद्या मुक्ति दिलाउँछ त्यही साँचो विद्या हो", "That knowledge is true which leads to liberation"),
    ],
    keyShlokas:     ["ॐ सरस्वत्यै नमः", "या कुन्देन्दुतुषारहारधवला..."],
    leelaHighlights: [],
    semanticAtomIds: ["jnana", "viveka", "dharma"],
    scriptureRefs:  ["Rigveda (Saraswati Suktam)", "Saraswati Vandana", "Devi Bhagavatam"],
    festivals:      ["सरस्वती पूजा / वसन्त पञ्चमी", "विजयादशमी (Vijayadashami)"],
    mantras:        ["ॐ ऐं सरस्वत्यै नमः", "या कुन्देन्दुतुषारहारधवला..."],
    canonicalMediaContext: "",
    primarySources: ["Rigveda", "Saraswati Vandana"],
    verified:       false,
    visibility:     "private",
  },

  // ── Lakshmi ───────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.lakshmi,
    characterType:  "deity",
    icon:           "🪷",
    chamberTheme:   "bhakti",
    primaryName:    ml("लक्ष्मी", "लक्ष्मी", "Lakshmi — Goddess of Abundance"),
    alternateNames: [
      ml("श्री", "श्री", "Shri — Auspiciousness Itself"),
      ml("पद्मा", "पद्मा", "Padma — The Lotus Goddess"),
      ml("कमला", "कमला", "Kamala — Born of the Lotus"),
      ml("हरिप्रिया", "हरिप्रिया", "Haripriya — Beloved of Vishnu"),
    ],
    epithets:       ["Bestower of Wealth and Grace", "Mother of the Universe"],
    traditions:     ["vaishnava", "shakta"],
    primaryTradition: "vaishnava",
    essence:        ml(
      "श्रीशक्तिः, सम्पद्दायिनी",
      "सम्पत्ति, समृद्धि, र अनुग्रहकी देवी — आन्तरिक र बाह्य दुवैको",
      "Goddess of abundance and grace — not merely material wealth but inner richness and divine favor",
    ),
    philosophicalNote: "Lakshmi is the shakti of Vishnu — she is inseparable from him. Where there is Vishnu (order, dharma, preservation), there Lakshmi (grace, abundance) naturally resides. She flees from those who are lazy, disrespectful of work, or who pursue wealth with greed.",
    devotionalNote: "Lakshmi is worshipped at Diwali as the light of prosperity entering newly cleaned homes. Her owl vahana (wisdom in darkness) reminds that wealth requires discernment. She holds lotus flowers — beauty rooted in mud, a reminder that abundance grows from effort in impure conditions.",
    symbols:        ["सुवर्ण कमल (golden lotus)", "स्वर्ण वर्षा (rain of gold coins)", "उलूक (owl vahana)", "हाथी (elephants bathing her)"],
    colors:         ["gold", "rose", "red"],
    iconographicDesc: "Lakshmi on a lotus, rose-gold complexion, four arms holding lotuses and raining gold coins. Two elephants on either side pouring water over her (Gaja-Lakshmi form). Adorned with jewels, silk garments. Serene, generous expression.",
    vehicleMount:   "उलूक / Owl",
    primaryRasa:    "madhurya",
    moods:          ["शान्त — the quiet abundance of grace", "वात्सल्य — as mother blessing her devotees"],
    coreTeachings:  [
      ml("धर्मेण अर्थः", "धर्मबाट मात्र साँचो सम्पत्ति प्राप्त हुन्छ", "True wealth comes only through righteous means"),
    ],
    keyShlokas:     ["श्री सूक्तम् — ऋग्वेद", "लक्ष्मी अष्टोत्तरशतनामावली"],
    leelaHighlights: [
      ml("समुद्र मन्थन", "समुद्र मन्थनबाट लक्ष्मीको प्रकट", "Lakshmi emerging from the Samudra Manthan (churning of the ocean) — born of cosmic effort"),
    ],
    spouseIds:      [SEED_IDS.vishnu],
    semanticAtomIds: ["dharma", "seva", "shakti"],
    scriptureRefs:  ["Sri Suktam (Rigveda)", "Vishnu Purana", "Devi Bhagavatam"],
    festivals:      ["दीपावली (Diwali)", "लक्ष्मी पूजा (Friday puja)", "कोजाग्रत पूर्णिमा"],
    mantras:        ["ॐ श्रीं महालक्ष्म्यै नमः", "श्री सूक्तम्"],
    canonicalMediaContext: "",
    primarySources: ["Sri Suktam", "Vishnu Purana"],
    verified:       false,
    visibility:     "private",
  },

  // ── Vishnu ────────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.vishnu,
    characterType:  "deity",
    icon:           "🔱",
    chamberTheme:   "default",
    primaryName:    ml("विष्णु", "विष्णु", "Vishnu — The All-Pervading Preserver"),
    alternateNames: [
      ml("नारायण", "नारायण", "Narayana — The Refuge of All Beings"),
      ml("हरि", "हरि", "Hari — Remover of Suffering"),
      ml("माधव", "माधव", "Madhava — The Eternal Spring"),
      ml("जगन्नाथ", "जगन्नाथ", "Jagannatha — Lord of the Universe"),
    ],
    epithets:       ["Preserver of Cosmic Order", "Source of All Avatars"],
    traditions:     ["vaishnava"],
    primaryTradition: "vaishnava",
    essence:        ml(
      "सर्वव्यापी परमात्मा, धर्मसंस्थापकः",
      "सर्वत्र व्याप्त परमात्मा, धर्मको रक्षक र पुनर्स्थापक",
      "The all-pervading supreme being — preserver of cosmic order, source of all divine incarnations",
    ),
    philosophicalNote: "Vishnu is the vishwa-rupa — the cosmic form pervading all space. His ten avatars (Dashavatara) represent dharma's response to each cosmic age. In each era of darkness, Vishnu descends to restore balance. Krishna and Rama are his most complete manifestations.",
    devotionalNote: "Vishnu rests on the cosmic serpent Shesha on the milk ocean — representing consciousness at rest, from which all creation emerges. He holds four objects: shankha (creative sound), chakra (dharma's wheel), lotus (beauty, purity), mace (strength). His dwelling is Vaikuntha — beyond suffering.",
    symbols:        ["सुदर्शन चक्र (Sudarshana Chakra)", "शंख पाञ्चजन्य (conch)", "पद्म (lotus)", "कौमोदकी गदा (mace)", "गरुड (Garuda vahana)", "शेष (cosmic serpent)"],
    colors:         ["blue", "gold"],
    iconographicDesc: "Vishnu with four arms, blue-black complexion, standing or reclining on Shesha Naga in the cosmic ocean. Holds Sudarshana Chakra, conch Panchajanya, lotus, and Kaumodaki mace. Crown (kireetam), yellow garments (pitambara), Kaustubha gem at chest. Garuda eagle as vahana.",
    vehicleMount:   "गरुड (Garuda — the eagle)",
    primaryRasa:    "shanta",
    moods:          ["शान्त — Vishnu in yogic sleep on Shesha (Yoga Nidra)", "वीर — as each avatar restoring dharma"],
    coreTeachings:  [
      ml("यदा यदा हि धर्मस्य", "जब जब धर्मको पतन हुन्छ, म आउँछु", "Whenever dharma declines, I descend — the promise of divine protection of righteousness"),
    ],
    keyShlokas:     [
      "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत... — Bhagavad Gita 4.7",
      "नारायण सुक्तम् — यज्ञवल्क्य",
    ],
    leelaHighlights: [
      ml("दशावतार", "दस अवतार — धर्मको संरक्षण", "Dashavatara — ten avatars across cosmic ages: Matsya, Kurma, Varaha, Narasimha, Vamana, Parashurama, Rama, Krishna, Buddha, Kalki"),
    ],
    spouseIds:      [SEED_IDS.lakshmi],
    childIds:       [],
    semanticAtomIds: ["dharma", "karma", "moksha"],
    scriptureRefs:  ["Vishnu Purana", "Bhagavata Purana", "Narayana Suktam", "Vishnu Sahasranama"],
    festivals:      ["वैकुण्ठ एकादशी", "जन्माष्टमी (as Krishna)", "राम नवमी (as Rama)"],
    mantras:        ["ॐ नमो नारायणाय", "ॐ नमो भगवते वासुदेवाय", "विष्णु सहस्रनाम"],
    canonicalMediaContext: "",
    primarySources: ["Vishnu Purana", "Bhagavata Purana"],
    verified:       false,
    visibility:     "private",
  },

  // ── Adi Shankaracharya ────────────────────────────────────────────────────

  {
    id:             SEED_IDS.shankaracharya,
    characterType:  "sage_acharya",
    icon:           "📿",
    chamberTheme:   "advaita",
    primaryName:    ml("आदि शंकराचार्य", "आदि शंकराचार्य", "Adi Shankaracharya"),
    alternateNames: [
      ml("आद्यशंकर", "आद्यशंकर", "Adyashankara — The Original Shankara"),
      ml("शङ्करभगवत्पाद", "शङ्करभगवत्पाद", "Shankara Bhagavatpada — Shankara at the feet of God"),
    ],
    epithets:       ["Founder of Advaita Vedanta", "Consolidator of Six Philosophical Schools", "Jagadguru"],
    traditions:     ["advaita_vedanta", "shaiva"],
    primaryTradition: "advaita_vedanta",
    essence:        ml(
      "अद्वैतवेदान्तप्रतिष्ठापकः",
      "अद्वैत वेदान्तका प्रतिष्ठापक — ब्रह्म र आत्मा एक हुन् भन्ने सिद्धान्त",
      "Establisher of Advaita Vedanta — the non-dual philosophical school asserting Brahman and Atman are one",
    ),
    philosophicalNote: "Shankaracharya synthesized the Upanishads, Brahma Sutras, and Bhagavad Gita into a coherent non-dual system. His core teaching: Brahman alone is real (Brahma satyam), the world is appearance (jagat mithya), the individual self is identical to Brahman (jivo brahmaiva naparah). Differences are superimpositions (adhyasa) on the one reality.",
    devotionalNote: "Despite being the philosopher of formless Brahman, Shankaracharya composed some of the most beautiful devotional hymns — Bhaja Govindam, Soundarya Lahari, Nirvana Shatakam. He showed that jnana (knowledge) and bhakti (devotion) are not opposed but complementary paths.",
    symbols:        ["दण्ड (monastic staff)", "कमण्डलु (water pot)", "भगवा (saffron robe)", "रुद्राक्ष (rudraksha)"],
    colors:         ["saffron", "deep-indigo"],
    iconographicDesc: "Shankaracharya as young sannyasi (he took sannyas at age 8, attained mahasamadhi at 32). Shaved head, saffron robes, holding danda (staff) and kamandalu (water pot). Serene countenance, seated in lotus posture.",
    primaryRasa:    "shanta",
    moods:          ["ज्ञान — the still clarity of non-dual awareness", "भक्ति — the devotional Shankara of Bhaja Govindam and hymns to Shiva"],
    coreTeachings:  [
      ml("ब्रह्म सत्यम् जगन्मिथ्या", "ब्रह्म मात्र सत्य हो, जगत मिथ्या हो", "Brahman alone is real, the world is appearance"),
      ml("जीवो ब्रह्मैव नापरः", "जीव नै ब्रह्म हो, अरू कोही होइन", "The individual self is none other than Brahman"),
      ml("तत् त्वम् असि", "तुम त्यही हो", "Thou art That — Chandogya Upanishad 6.8.7"),
      ml("अहं ब्रह्मास्मि", "म ब्रह्म हुँ", "I am Brahman — Brihadaranyaka Upanishad 1.4.10"),
    ],
    keyShlokas:     [
      "भज गोविन्दं भज गोविन्दं, गोविन्दं भज मूढमते...",
      "निर्वाण षट्कम्: चिदानन्दरूपः शिवोऽहं शिवोऽहम्",
      "ब्रह्म सत्यं जगन्मिथ्या जीवो ब्रह्मैव नापरः",
    ],
    leelaHighlights: [
      ml("विवेकचूडामणि", "अद्वैतको उत्कृष्ट ग्रन्थ रचना", "Composing Vivekachudamani — the crown jewel of discrimination, the greatest text of Advaita Vedanta"),
      ml("चार मठ स्थापना", "चार दिशामा मठ स्थापना", "Establishing four mathas (monasteries) at four corners of India — Sringeri, Dwarka, Puri, Joshimath"),
      ml("माण्डन मिश्र वाद-विवाद", "माण्डन मिश्रसँग शास्त्रार्थ", "The great debate with Mandana Mishra — establishing Advaita over Mimamsa"),
    ],
    shishyaIds:     [],
    semanticAtomIds: ["advaita", "moksha", "maya", "brahman", "atman", "viveka"],
    scriptureRefs:  ["Vivekachudamani", "Brahmasutra Bhashya", "Upanishad Bhashyas (Isha, Kena, Katha, Mundaka, Mandukya)", "Bhagavad Gita Bhashya", "Bhaja Govindam", "Soundarya Lahari"],
    bhajanRefs:     ["भज गोविन्दम्", "निर्वाण षट्कम्", "शिवपञ्चाक्षरस्तोत्रम्"],
    festivals:      ["शंकराचार्य जयन्ती (Shankaracharya Jayanti — Vaishakha Shukla Panchami)"],
    mantras:        ["अहं ब्रह्मास्मि", "तत् त्वम् असि", "शिवोऽहं शिवोऽहम्"],
    canonicalMediaContext: "",
    primarySources: ["Vivekachudamani", "Brahmasutra Bhashya", "Upanishad Bhashyas"],
    verified:       false,
    visibility:     "private",
  },

  // ── Buddha ────────────────────────────────────────────────────────────────

  {
    id:             SEED_IDS.buddha,
    characterType:  "sage_acharya",
    icon:           "☮",
    chamberTheme:   "buddha",
    primaryName:    ml("बुद्ध", "बुद्ध", "Buddha — The Awakened One"),
    alternateNames: [
      ml("तथागत", "तथागत", "Tathagata — Thus Gone / Thus Come"),
      ml("शाक्यमुनि", "शाक्यमुनि", "Shakyamuni — Sage of the Shakya clan"),
      ml("सिद्धार्थ गौतम", "सिद्धार्थ गौतम", "Siddhartha Gautama — historical name"),
      ml("धर्मराज", "धर्मराज", "Dharmaraja — King of Dharma"),
    ],
    epithets:       ["The Awakened One", "Compassion Embodied", "Ninth Avatar of Vishnu (in Hindu tradition)"],
    traditions:     ["buddhist"],
    primaryTradition: "buddhist",
    essence:        ml(
      "बुद्धं शरणं गच्छामि",
      "जागृति, करुणा, र अनित्यताको गहन बोध — दुःखबाट मुक्तिको मार्ग",
      "Awakening, compassion, and deep awareness of impermanence — the path to liberation from suffering",
    ),
    philosophicalNote: "The Buddha's core insight is Pratityasamutpada (dependent origination) — all phenomena arise in dependence on other phenomena; nothing has fixed, independent existence. This leads to Sunyata (emptiness), Anatman (no-self), and Anicca (impermanence). The Eightfold Path is the practical road to liberation.",
    devotionalNote: "In Nepal, Buddha is both the founder of Buddhism (born at Lumbini, Nepal) and revered in Hindu tradition as the ninth avatar of Vishnu. His teaching of karuna (compassion) and metta (loving-kindness) remains one of humanity's most accessible spiritual paths.",
    symbols:        ["बोधिवृक्ष (Bodhi tree)", "धर्मचक्र (Dharma Wheel)", "कमल (lotus)", "भिक्षापात्र (begging bowl)", "हस्तमुद्रा (hand mudras — dhyana, bhumisparsha, varada)"],
    colors:         ["saffron", "gold", "stone-grey"],
    iconographicDesc: "Gautama Buddha in meditation posture (dhyana mudra) or in bhumisparsha mudra (touching the earth at moment of enlightenment). Shaved head, saffron robes. Serene expression. Seated under the Bodhi tree or on a lotus. Elongated earlobes (from princely past), ushnisha on crown.",
    primaryRasa:    "karuna",
    moods:          ["शान्त — in deep samadhi under the Bodhi tree", "करुण — teaching the four noble truths with compassion", "आनन्द — in nirvana beyond all suffering"],
    coreTeachings:  [
      ml("चत्वारि आर्यसत्यानि", "चार आर्य सत्य", "The Four Noble Truths: existence is suffering (dukkha), suffering has a cause (craving), there is an end to suffering, the Eightfold Path leads there"),
      ml("अहिंसा परमो धर्मः", "अहिंसा परम धर्म हो", "Non-violence is the highest dharma"),
      ml("सर्वे प्राणिनः सुखं प्राप्नुवन्तु", "सबै प्राणीहरू सुखी होऊन्", "May all beings be happy — the metta (loving-kindness) prayer"),
    ],
    keyShlokas:     [
      "बुद्धं शरणं गच्छामि, धम्मं शरणं गच्छामि, संघं शरणं गच्छामि",
      "सब्बे सत्ता सुखिता होन्तु — मेत्ता सुत्त",
    ],
    leelaHighlights: [
      ml("महाभिनिष्क्रमण", "राजमहलबाट त्याग", "The Great Renunciation — leaving the palace at night, cutting hair, taking saffron robes"),
      ml("बोधि प्राप्ति", "बोधगया मा ज्ञान प्राप्ति", "Enlightenment under the Bodhi Tree at Bodh Gaya — after 49 days of deep meditation"),
      ml("धर्मचक्रप्रवर्तन", "सारनाथमा प्रथम उपदेश", "First sermon at Sarnath (Deer Park) — setting the Dharma Wheel in motion"),
    ],
    semanticAtomIds: ["dharma", "karma", "moksha", "ahimsa", "karuna", "anicca"],
    scriptureRefs:  ["Dhammapada (Pali Canon)", "Tripitaka", "Majjhima Nikaya", "Samyutta Nikaya"],
    festivals:      ["बुद्ध पूर्णिमा (Buddha Purnima — born, enlightened, attained Parinirvana on same day)", "Losar (Tibetan New Year)"],
    mantras:        ["ॐ मणि पद्मे हूम्", "बुद्धं शरणं गच्छामि", "ॐ अहं वज्रसत्त्व समयम्..."],
    canonicalMediaContext: "",
    primarySources: ["Dhammapada", "Majjhima Nikaya", "Tripitaka"],
    verified:       false,
    visibility:     "private",
  },
];

// ── Core relationship seeds ────────────────────────────────────────────────────

export const SPIRITUAL_RELATIONSHIP_SEEDS: Array<Omit<SpiritualRelationship, "ownerId" | "createdAt"> & { id: string }> = [
  {
    id:           "rel_shiva_parvati",
    fromId:       SEED_IDS.shiva, fromType: "character", fromName: "शिव",
    toId:         SEED_IDS.parvati, toType: "character", toName: "पार्वती",
    relationType: "loves",
    contextNote:  ml("शिव-शक्ति अर्धनारीश्वर", "शिव र पार्वती अर्धनारीश्वर रूपमा एक छन्", "Shiva and Parvati are one as Ardhanarishvara — the complete being of consciousness and energy"),
    scriptureRef: "Shiva Purana",
    verified:     false,
  },
  {
    id:           "rel_shiva_ganesha",
    fromId:       SEED_IDS.shiva, fromType: "character", fromName: "शिव",
    toId:         SEED_IDS.ganesha, toType: "character", toName: "गणेश",
    relationType: "participated_in",
    contextNote:  ml("", "शिव-पार्वतीका पुत्र गणेश", "Ganesha is the son of Shiva and Parvati — born from Parvati's clay, given elephant head by Shiva"),
    scriptureRef: "Shiva Purana",
    verified:     false,
  },
  {
    id:           "rel_vishnu_krishna",
    fromId:       SEED_IDS.vishnu, fromType: "character", fromName: "विष्णु",
    toId:         SEED_IDS.krishna, toType: "character", toName: "कृष्ण",
    relationType: "incarnation_of",
    contextNote:  ml("", "कृष्ण विष्णुको अष्टम अवतार हुन्", "Krishna is the eighth (most complete) avatar of Vishnu — the Purna Avatar"),
    scriptureRef: "Bhagavata Purana",
    verified:     false,
  },
  {
    id:           "rel_vishnu_rama",
    fromId:       SEED_IDS.vishnu, fromType: "character", fromName: "विष्णु",
    toId:         SEED_IDS.rama, toType: "character", toName: "राम",
    relationType: "incarnation_of",
    contextNote:  ml("", "राम विष्णुको सप्तम अवतार हुन्", "Rama is the seventh avatar of Vishnu — the Maryada Purushottama avatar"),
    scriptureRef: "Valmiki Ramayana",
    verified:     false,
  },
  {
    id:           "rel_vishnu_lakshmi",
    fromId:       SEED_IDS.vishnu, fromType: "character", fromName: "विष्णु",
    toId:         SEED_IDS.lakshmi, toType: "character", toName: "लक्ष्मी",
    relationType: "loves",
    contextNote:  ml("", "लक्ष्मी विष्णुकी शक्ति हुन्", "Lakshmi is the eternal consort and shakti of Vishnu — present in every avatar"),
    scriptureRef: "Vishnu Purana",
    verified:     false,
  },
  {
    id:           "rel_rama_hanuman",
    fromId:       SEED_IDS.rama, fromType: "character", fromName: "राम",
    toId:         SEED_IDS.hanuman, toType: "character", toName: "हनुमान",
    relationType: "blesses",
    contextNote:  ml("", "राम हनुमानलाई आफ्नो भाइसरह माया गर्नुहुन्छ", "Rama's bond with Hanuman — the blessed servant becomes the ideal devotee, greater than all"),
    scriptureRef: "Valmiki Ramayana",
    verified:     false,
  },
  {
    id:           "rel_krishna_radha",
    fromId:       SEED_IDS.krishna, fromType: "character", fromName: "कृष्ण",
    toId:         SEED_IDS.radha, toType: "character", toName: "राधा",
    relationType: "loves",
    contextNote:  ml("", "राधा-कृष्ण — दिव्य प्रेमको उच्चतम प्रतीक", "Radha-Krishna — the highest symbol of divine love; Radha is Krishna's own bliss-shakti (hladini-shakti)"),
    scriptureRef: "Gita Govinda (Jayadeva)",
    verified:     false,
  },
  {
    id:           "rel_shankaracharya_advaita",
    fromId:       SEED_IDS.shankaracharya, fromType: "character", fromName: "शंकराचार्य",
    toId:         "advaita", toType: "atom", toName: "अद्वैत",
    relationType: "teaches",
    contextNote:  ml("", "शंकराचार्यले अद्वैत वेदान्तको प्रतिष्ठापन गर्नुभयो", "Shankaracharya established Advaita Vedanta — the non-dual philosophy through his Brahmasutra Bhashya and Upanishad commentaries"),
    scriptureRef: "Brahmasutra Bhashya",
    verified:     false,
  },
  {
    id:           "rel_shankaracharya_vivekachudamani",
    fromId:       SEED_IDS.shankaracharya, fromType: "character", fromName: "शंकराचार्य",
    toId:         "vivekachudamani", toType: "scripture", toName: "विवेकचूडामणि",
    relationType: "composed",
    contextNote:  ml("", "विवेकचूडामणि — अद्वैतको उत्कृष्ट ग्रन्थ", "Vivekachudamani — The Crown Jewel of Discrimination — composed by Shankaracharya, the greatest text on Advaita Vedanta"),
    verified:     false,
  },
  {
    id:           "rel_krishna_gita",
    fromId:       SEED_IDS.krishna, fromType: "character", fromName: "कृष्ण",
    toId:         "bhagavad_gita", toType: "scripture", toName: "भगवद्गीता",
    relationType: "reveals",
    contextNote:  ml("", "कृष्णले अर्जुनलाई भगवद्गीताको उपदेश दिनुभयो", "Krishna revealed the Bhagavad Gita to Arjuna on the battlefield of Kurukshetra — 700 verses, 18 chapters"),
    scriptureRef: "Bhagavad Gita",
    verified:     false,
  },
];
